apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: app13-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: app13

  namespaceSelector:
    matchNames:
      - web13

  endpoints:
    - port: http
      path: /metrics
      interval: 15s