apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-ac-576-220239-v13
  namespace: state-ac-576-220239-v13

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi