apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: state-ac-576-220239-v13
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
  POSTGRES_DB: studentdb